name: Build and Publish Docker Image

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!Readme.md'
      - '!**/.git/**'
      - '!**/.gitignore'
      - '!ISSUE_TEMPLATE/**'

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2


      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: dodoooh/plexopener:latest
          dockerfile: Dockerfile
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_HUB_USERNAME }}
          DOCKER_PASSWORD: ${{ secrets.DOCKER_HUB_PASSWORD }}